### ISSUE TITLE
[Feature Request] Add cross-platform key combination for saving pastes

### ISSUE THREAD

**Issue by whalehub** [w4/bin#10]
The current key combination for saving a paste unfortunately cannot be executed on Windows or Linux machines since the ⌘ key is only available on a macOS keyboard. The pastebin software [Haste](https://github.com/seejohnrun/haste-server), for example, uses the cross-platform key combination **CTRL+S** for saving a paste.

It would be great if that one could be added as an alternative to the current key combination.

**Comment by w4** [comment]
The code currently just [targets any modifier key](https://github.com/w4/bin/blob/9c53294b88d970d0438e8772eb2c0865d04fe756/templates/index.html#L59) including ctrl, alt and meta keys. Maybe the shortcut hints should be a little less Mac-specific though :)

Thanks for the issue

**Comment by whalehub** [comment]
@w4 On https://bin.gy/ and my selfhosted instance, pressing CTRL+A selects all text and ALT+A does nothing. This is using Chrome v80.0.3987.163 with no extensions.

**Comment by whalehub** [comment]
Nevermind, I just noticed that the shortcut for saving a paste is `Modifier Key` + `Enter` (not sure what the one the description is referring to does). It works for me this way. Thanks!
