### ISSUE TITLE
Document endpoints in the README

### ISSUE THREAD

**Issue by Julien00859** [w4/bin#2]
Hello,

Quick question, is there any reason you decided to use `PUT` to publish a paste and not `POST` ? Although there is no problem from the perspective of the http rfc to use `PUT` to create a new record, `POST` is more common.

Actually, whould it be possible to list all the http routes (verb + endpoint + payload + description) in the readme ? I'm not fluent with rust/rocket so I'm not confident to look for answer in the source code.

Btw, thank you for your minimalist bin, it really rocks ! :)

**Comment by Julien00859** [comment]
I think I understand better... `POST` is used by the frontend already.

**Comment by w4** [comment]
Got it in one! :) `POST` expects a form submission whereas `PUT` expects the raw paste in the body. Good shout on the routes, I'll get those in the readme for you.
