### ISSUE TITLE
Demo Site is down

### ISSUE THREAD

**Issue by worldworm** [w4/bin#3]
your demo page is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by worldworm** [comment]
ping @w4

**Comment by w4** [comment]
Sorry @worldworm, this was hosted on a box in my flat but I'm currently between houses while I wait for my mortgage to go through. Should be 2 weeks now hopefully until I get the keys so it'll be back up then!

**Comment by worldworm** [comment]
Unfortunately this demopage was removed from awesome-selfhosted due to inactivity. You can add this site at any time should it become active again.
Thanks for your understanding!

https://github.com/awesome-selfhosted/awesome-selfhosted
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1838
